### ISSUE TITLE
instructions to read, parse, load an mt942 file

### ISSUE THREAD

**Issue by bitcoinsSG** [gingerpayments/python-libmt94x#1]
Is this functionality available? and if so can you provide some instructions on how to go about it?

**Comment by numerodix** [comment]
No, the goal of this project is to produce libmt940 files, not to parse them. There are other projects around that provide parsers. See here:
https://pypi.python.org/pypi?%3Aaction=search&term=mt940&submit=search

**Comment by bitcoinsSG** [comment]
ok, thanks. Tried most of them. They don't seem to parse 942s.
